// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dbr

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type VenuesStatus string

const (
	VenuesStatusOpen   VenuesStatus = "open"
	VenuesStatusClosed VenuesStatus = "closed"
)

func (e *VenuesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VenuesStatus(s)
	case string:
		*e = VenuesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VenuesStatus: %T", src)
	}
	return nil
}

type NullVenuesStatus struct {
	VenuesStatus VenuesStatus
	Valid        bool // Valid is true if VenuesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVenuesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VenuesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VenuesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVenuesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VenuesStatus), nil
}

type City struct {
	Slug string
	Name string
}

// Venues are places where muisc happens
type Venue struct {
	ID int64
	// Venues can be either open or closed
	Status   VenuesStatus
	Statuses sql.NullString
	// This value appears in public URLs
	Slug            string
	Name            string
	City            string
	SpotifyPlaylist string
	SongkickID      sql.NullString
	Tags            sql.NullString
	CreatedAt       time.Time
}
