// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir v3.1.1

package v1

import (
	"net/http"

	"github.com/alimy/mir/v3"
	"github.com/gin-gonic/gin"
	"github.com/rocboss/paopao-ce/internal/model/web"
)

type Admin interface {
	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	ChangeUserStatus(*web.ChangeUserStatusReq) mir.Error

	mustEmbedUnimplementedAdminServant()
}

type AdminBinding interface {
	BindChangeUserStatus(*gin.Context) (*web.ChangeUserStatusReq, mir.Error)

	mustEmbedUnimplementedAdminBinding()
}

type AdminRender interface {
	RenderChangeUserStatus(*gin.Context, mir.Error)

	mustEmbedUnimplementedAdminRender()
}

// RegisterAdminServant register Admin servant to gin
func RegisterAdminServant(e *gin.Engine, s Admin, b AdminBinding, r AdminRender) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("POST", "/admin/user/status", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		req, err := b.BindChangeUserStatus(c)
		if err != nil {
			r.RenderChangeUserStatus(c, err)
			return
		}
		r.RenderChangeUserStatus(c, s.ChangeUserStatus(req))
	})

}

// UnimplementedAdminServant can be embedded to have forward compatible implementations.
type UnimplementedAdminServant struct {
}

func (UnimplementedAdminServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedAdminServant) ChangeUserStatus(req *web.ChangeUserStatusReq) mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) mustEmbedUnimplementedAdminServant() {}

// UnimplementedAdminRender can be embedded to have forward compatible implementations.
type UnimplementedAdminRender struct {
	RenderAny func(*gin.Context, any, mir.Error)
}

func (r *UnimplementedAdminRender) RenderChangeUserStatus(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedAdminRender) mustEmbedUnimplementedAdminRender() {}

// UnimplementedAdminBinding can be embedded to have forward compatible implementations.
type UnimplementedAdminBinding struct {
	BindAny func(*gin.Context, any) mir.Error
}

func (b *UnimplementedAdminBinding) BindChangeUserStatus(c *gin.Context) (*web.ChangeUserStatusReq, mir.Error) {
	obj := new(web.ChangeUserStatusReq)
	err := b.BindAny(c, obj)
	return obj, err
}

func (b *UnimplementedAdminBinding) mustEmbedUnimplementedAdminBinding() {}
