// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir 5.3

package v1

import (
	"net/http"

	"github.com/alimy/mir/v5"
	"github.com/gin-gonic/gin"
	"github.com/rocboss/paopao-ce/internal/model/web"
)

type Blockship interface {
	_default_

	ListBlocks(*web.ListBlocksReq) (*web.ListBlocksResp, error)
	UnblockUser(*web.UnblockUserReq) error
	BlockUser(*web.BlockUserReq) error

	mustEmbedUnimplementedBlockshipServant()
}

// RegisterBlockshipServant register Blockship servant to gin
func RegisterBlockshipServant(e *gin.Engine, s Blockship) {
	router := e.Group("v1")

	// register routes info to router
	router.Handle("GET", "user/blocks", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.ListBlocksReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.ListBlocks(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "user/unblock", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.UnblockUserReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.UnblockUser(req))
	})
	router.Handle("POST", "user/block", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.BlockUserReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.BlockUser(req))
	})
}

// UnimplementedBlockshipServant can be embedded to have forward compatible implementations.
type UnimplementedBlockshipServant struct{}

func (UnimplementedBlockshipServant) ListBlocks(req *web.ListBlocksReq) (*web.ListBlocksResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedBlockshipServant) UnblockUser(req *web.UnblockUserReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedBlockshipServant) BlockUser(req *web.BlockUserReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedBlockshipServant) mustEmbedUnimplementedBlockshipServant() {}
