// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir v4.0.0

package v1

import (
	"net/http"

	"github.com/alimy/mir/v4"
	"github.com/gin-gonic/gin"
	"github.com/rocboss/paopao-ce/internal/model/web"
)

type Followship interface {
	_default_

	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	ListFollowers(*web.ListFollowersReq) (*web.ListFollowersResp, mir.Error)
	ListFollowings(*web.ListFollowingsReq) (*web.ListFollowingsResp, mir.Error)
	DeleteFollowing(*web.DeleteFollowingReq) mir.Error
	AddFollowing(*web.AddFollowingReq) mir.Error

	mustEmbedUnimplementedFollowshipServant()
}

// RegisterFollowshipServant register Followship servant to gin
func RegisterFollowshipServant(e *gin.Engine, s Followship) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("GET", "/follower/list", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		var (
			obj any
			err mir.Error
		)
		req := new(web.ListFollowersReq)
		obj = req
		if bv, ok := obj.(_binding_); !ok {
			err = s.Bind(c, req)
		} else {
			err = bv.Bind(c)
		}
		if err != nil {
			s.Render(c, nil, err)
			return
		}
		obj, err = s.ListFollowers(req)
		if err != nil {
			s.Render(c, nil, err)
			return
		}
		if rv, ok := obj.(_render_); !ok {
			s.Render(c, obj, nil)
		} else {
			rv.Render(c)
		}
	})
	router.Handle("GET", "/following/list", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		var (
			obj any
			err mir.Error
		)
		req := new(web.ListFollowingsReq)
		obj = req
		if bv, ok := obj.(_binding_); !ok {
			err = s.Bind(c, req)
		} else {
			err = bv.Bind(c)
		}
		if err != nil {
			s.Render(c, nil, err)
			return
		}
		obj, err = s.ListFollowings(req)
		if err != nil {
			s.Render(c, nil, err)
			return
		}
		if rv, ok := obj.(_render_); !ok {
			s.Render(c, obj, nil)
		} else {
			rv.Render(c)
		}
	})
	router.Handle("POST", "/following/delete", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		var (
			obj any
			err mir.Error
		)
		req := new(web.DeleteFollowingReq)
		obj = req
		if bv, ok := obj.(_binding_); !ok {
			err = s.Bind(c, req)
		} else {
			err = bv.Bind(c)
		}
		if err != nil {
			s.Render(c, nil, err)
			return
		}

		s.Render(c, nil, s.DeleteFollowing(req))
	})
	router.Handle("POST", "/following/add", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		var (
			obj any
			err mir.Error
		)
		req := new(web.AddFollowingReq)
		obj = req
		if bv, ok := obj.(_binding_); !ok {
			err = s.Bind(c, req)
		} else {
			err = bv.Bind(c)
		}
		if err != nil {
			s.Render(c, nil, err)
			return
		}

		s.Render(c, nil, s.AddFollowing(req))
	})
}

// UnimplementedFollowshipServant can be embedded to have forward compatible implementations.
type UnimplementedFollowshipServant struct{}

func (UnimplementedFollowshipServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedFollowshipServant) ListFollowers(req *web.ListFollowersReq) (*web.ListFollowersResp, mir.Error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedFollowshipServant) ListFollowings(req *web.ListFollowingsReq) (*web.ListFollowingsResp, mir.Error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedFollowshipServant) DeleteFollowing(req *web.DeleteFollowingReq) mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedFollowshipServant) AddFollowing(req *web.AddFollowingReq) mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedFollowshipServant) mustEmbedUnimplementedFollowshipServant() {}
