// Code generated by go-mir. DO NOT EDIT.

package v1

import (
	"net/http"

	"github.com/alimy/mir/v3"
	"github.com/gin-gonic/gin"
	"github.com/rocboss/paopao-ce/internal/model/web"
)

type Priv interface {
	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	DeleteCommentReply() mir.Error
	CreateCommentReply() mir.Error
	DeleteComment() mir.Error
	CreateComment() mir.Error
	VisiblePost() mir.Error
	StickTweet() mir.Error
	LockTweet() mir.Error
	CollectionTweet() mir.Error
	StarTweet() mir.Error
	DeleteTweet() mir.Error
	CreateTweet(*web.CreateTweetReq) (*web.CreateTweetResp, mir.Error)
	DownloadAttachment() mir.Error
	DownloadAttachmentPrecheck() mir.Error
	UploadAttachment() mir.Error

	mustEmbedUnimplementedPrivServant()
}

type PrivBinding interface {
	BindCreateTweet(*gin.Context) (*web.CreateTweetReq, mir.Error)

	mustEmbedUnimplementedPrivBinding()
}

type PrivRender interface {
	RenderDeleteCommentReply(*gin.Context, mir.Error)
	RenderCreateCommentReply(*gin.Context, mir.Error)
	RenderDeleteComment(*gin.Context, mir.Error)
	RenderCreateComment(*gin.Context, mir.Error)
	RenderVisiblePost(*gin.Context, mir.Error)
	RenderStickTweet(*gin.Context, mir.Error)
	RenderLockTweet(*gin.Context, mir.Error)
	RenderCollectionTweet(*gin.Context, mir.Error)
	RenderStarTweet(*gin.Context, mir.Error)
	RenderDeleteTweet(*gin.Context, mir.Error)
	RenderCreateTweet(*gin.Context, *web.CreateTweetResp, mir.Error)
	RenderDownloadAttachment(*gin.Context, mir.Error)
	RenderDownloadAttachmentPrecheck(*gin.Context, mir.Error)
	RenderUploadAttachment(*gin.Context, mir.Error)

	mustEmbedUnimplementedPrivRender()
}

// RegisterPrivServant register Priv servant to gin
func RegisterPrivServant(e *gin.Engine, s Priv, b PrivBinding, r PrivRender) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("DELETE", "/post/comment/reply", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderDeleteCommentReply(c, s.DeleteCommentReply())
	})

	router.Handle("POST", "/post/comment/reply", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderCreateCommentReply(c, s.CreateCommentReply())
	})

	router.Handle("DELETE", "/post/comment", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderDeleteComment(c, s.DeleteComment())
	})

	router.Handle("POST", "/post/comment", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderCreateComment(c, s.CreateComment())
	})

	router.Handle("POST", "/post/visibility", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderVisiblePost(c, s.VisiblePost())
	})

	router.Handle("POST", "/post/stick", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderStickTweet(c, s.StickTweet())
	})

	router.Handle("POST", "/post/lock", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderLockTweet(c, s.LockTweet())
	})

	router.Handle("POST", "/post/collection", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderCollectionTweet(c, s.CollectionTweet())
	})

	router.Handle("POST", "/post/start", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderStarTweet(c, s.StarTweet())
	})

	router.Handle("DELETE", "/post", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderDeleteTweet(c, s.DeleteTweet())
	})

	router.Handle("POST", "/post", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		req, err := b.BindCreateTweet(c)
		if err != nil {
			r.RenderCreateTweet(c, nil, err)
			return
		}
		resp, err := s.CreateTweet(req)
		r.RenderCreateTweet(c, resp, err)
	})

	router.Handle("GET", "/attachment", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderDownloadAttachment(c, s.DownloadAttachment())
	})

	router.Handle("GET", "/attachment/precheck", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderDownloadAttachmentPrecheck(c, s.DownloadAttachmentPrecheck())
	})

	router.Handle("POST", "/attachment", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		r.RenderUploadAttachment(c, s.UploadAttachment())
	})

}

// UnimplementedPrivServant can be embedded to have forward compatible implementations.
type UnimplementedPrivServant struct {
}

func (UnimplementedPrivServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedPrivServant) DeleteCommentReply() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) CreateCommentReply() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) DeleteComment() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) CreateComment() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) VisiblePost() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) StickTweet() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) LockTweet() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) CollectionTweet() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) StarTweet() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) DeleteTweet() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) CreateTweet(req *web.CreateTweetReq) (*web.CreateTweetResp, mir.Error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) DownloadAttachment() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) DownloadAttachmentPrecheck() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) UploadAttachment() mir.Error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedPrivServant) mustEmbedUnimplementedPrivServant() {}

// UnimplementedPrivRender can be embedded to have forward compatible implementations.
type UnimplementedPrivRender struct {
	RenderAny func(*gin.Context, any, mir.Error)
}

func (r *UnimplementedPrivRender) RenderDeleteCommentReply(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderCreateCommentReply(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderDeleteComment(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderCreateComment(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderVisiblePost(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderStickTweet(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderLockTweet(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderCollectionTweet(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderStarTweet(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderDeleteTweet(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderCreateTweet(c *gin.Context, data *web.CreateTweetResp, err mir.Error) {
	r.RenderAny(c, data, err)
}

func (r *UnimplementedPrivRender) RenderDownloadAttachment(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderDownloadAttachmentPrecheck(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) RenderUploadAttachment(c *gin.Context, err mir.Error) {
	r.RenderAny(c, nil, err)
}

func (r *UnimplementedPrivRender) mustEmbedUnimplementedPrivRender() {}

// UnimplementedPrivBinding can be embedded to have forward compatible implementations.
type UnimplementedPrivBinding struct {
	BindAny func(*gin.Context, any) mir.Error
}

func (b *UnimplementedPrivBinding) BindCreateTweet(c *gin.Context) (*web.CreateTweetReq, mir.Error) {
	obj := new(web.CreateTweetReq)
	err := b.BindAny(c, obj)
	return obj, err
}

func (b *UnimplementedPrivBinding) mustEmbedUnimplementedPrivBinding() {}
