// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dbr

import ()

// 主题标签
type PTag struct {
	ID         int64
	UserID     int64
	Tag        string
	QuoteNum   int64
	CreatedOn  int32
	ModifiedOn int32
	DeletedOn  int32
	// 是否删除
	IsDel bool
}
