// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dbr

import (
	"database/sql"
	"time"
)

type City struct {
	Slug string
	Name string
}

type Venue struct {
	ID              int64
	Status          string
	Statuses        sql.NullString
	Slug            string
	Name            string
	City            string
	SpotifyPlaylist string
	SongkickID      sql.NullString
	Tags            sql.NullString
	CreatedAt       time.Time
}
