PRAGMA foreign_keys = false;

DROP INDEX IF EXISTS "idx_attachment_user_id";
DROP INDEX IF EXISTS "idx_captcha_expired_on";
DROP INDEX IF EXISTS "idx_captcha_phone";
DROP INDEX IF EXISTS "idx_captcha_use_times";
DROP INDEX IF EXISTS "idx_comment_post_id";
DROP INDEX IF EXISTS "idx_comment_user_id";
DROP INDEX IF EXISTS "idx_comment_content_comment_id";
DROP INDEX IF EXISTS "idx_comment_content_sort";
DROP INDEX IF EXISTS "idx_comment_content_type";
DROP INDEX IF EXISTS "idx_comment_content_user_id";
DROP INDEX IF EXISTS "idx_comment_reply_comment_id";
DROP INDEX IF EXISTS "idx_contact_user_friend";
DROP INDEX IF EXISTS "idx_contact_user_friend_status";
DROP INDEX IF EXISTS "idx_message_is_read";
DROP INDEX IF EXISTS "idx_message_receiver_user_id";
DROP INDEX IF EXISTS "idx_message_type";
DROP INDEX IF EXISTS "idx_post_user_id";
DROP INDEX IF EXISTS "idx_post_visibility";
DROP INDEX IF EXISTS "idx_post_attachment_bill_post_id";
DROP INDEX IF EXISTS "idx_post_attachment_bill_user_id";
DROP INDEX IF EXISTS "idx_post_collection_post_id";
DROP INDEX IF EXISTS "idx_post_collection_user_id";
DROP INDEX IF EXISTS "idx_post_content_post_id";
DROP INDEX IF EXISTS "idx_post_content_user_id";
DROP INDEX IF EXISTS "idx_post_star_post_id";
DROP INDEX IF EXISTS "idx_post_star_user_id";
DROP INDEX IF EXISTS "idx_tag";
DROP INDEX IF EXISTS "idx_tag_quote_num";
DROP INDEX IF EXISTS "idx_tag_user_id";
DROP INDEX IF EXISTS "idx_user_phone";
DROP INDEX IF EXISTS "idx_user_username";
DROP INDEX IF EXISTS "idx_wallet_recharge_trade_no";
DROP INDEX IF EXISTS "idx_wallet_recharge_trade_status";
DROP INDEX IF EXISTS "idx_wallet_recharge_user_id";
DROP INDEX IF EXISTS "idx_wallet_statement_user_id";

PRAGMA foreign_keys = true;
