// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package pg

import (
	"context"
)

type Querier interface {
	//------------------------------------------------------------------------------
	// core global sql dml
	//------------------------------------------------------------------------------
	IndexByAdmin(ctx context.Context, arg *IndexByAdminParams) ([]*PPost, error)
}

var _ Querier = (*Queries)(nil)
