CREATE TABLE `p_site_settings` (
	`id` BIGINT NOT NULL DEFAULT 1,
	`use_friendship` TINYINT NOT NULL DEFAULT 0,
	`enable_trends_bar` TINYINT NOT NULL DEFAULT 0,
	`enable_wallet` TINYINT NOT NULL DEFAULT 0,
	`allow_tweet_attachment` TINYINT NOT NULL DEFAULT 0,
	`allow_tweet_attachment_price` TINYINT NOT NULL DEFAULT 0,
	`allow_tweet_video` TINYINT NOT NULL DEFAULT 0,
	`default_tweet_max_length` INT NOT NULL DEFAULT 2000,
	`tweet_web_ellipsis_size` INT NOT NULL DEFAULT 400,
	`tweet_mobile_ellipsis_size` INT NOT NULL DEFAULT 300,
	`default_tweet_visibility` VARCHAR(32) NOT NULL DEFAULT 'friend',
	`default_msg_loop_interval` INT NOT NULL DEFAULT 5000,
	`copyright_top` VARCHAR(255) NOT NULL DEFAULT '',
	`copyright_left` VARCHAR(255) NOT NULL DEFAULT '',
	`copyright_left_link` VARCHAR(255) NOT NULL DEFAULT '',
	`copyright_right` VARCHAR(255) NOT NULL DEFAULT '',
	`copyright_right_link` VARCHAR(255) NOT NULL DEFAULT '',
	`created_on` BIGINT NOT NULL DEFAULT 0,
	`modified_on` BIGINT NOT NULL DEFAULT 0,
	`deleted_on` BIGINT NOT NULL DEFAULT 0,
	`is_del` TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='站点配置';
