// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dbr

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PAttachment struct {
	ID         int64
	UserID     int64
	FileSize   int64
	ImgWidth   int64
	ImgHeight  int64
	Type       int16
	Content    string
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
}

type PCaptcha struct {
	ID         int64
	Phone      pgtype.Text
	Captcha    pgtype.Text
	UseTimes   int32
	ExpiredOn  int64
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
}

type PComment struct {
	ID         int64
	PostID     int64
	UserID     int64
	Ip         string
	IpLoc      string
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
}

type PCommentContent struct {
	ID         int64
	CommentID  int64
	UserID     int64
	Content    string
	Type       int16
	Sort       int64
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
}

type PCommentReply struct {
	ID         int64
	CommentID  int64
	UserID     int64
	AtUserID   int64
	Content    string
	Ip         string
	IpLoc      string
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
}

type PContact struct {
	ID           int64
	UserID       int64
	FriendID     int64
	GroupID      int64
	Remark       string
	Status       int16
	IsTop        int16
	IsBlack      int16
	IsDel        int16
	NoticeEnable int16
	CreatedOn    int64
	ModifiedOn   int64
	DeletedOn    int64
}

type PContactGroup struct {
	ID         int64
	UserID     int32
	Name       string
	IsDel      int16
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
}

type PMessage struct {
	ID             int64
	SenderUserID   int64
	ReceiverUserID int64
	Type           int16
	Brief          string
	Content        string
	PostID         int64
	CommentID      int64
	ReplyID        int64
	IsRead         int16
	CreatedOn      int64
	ModifiedOn     int64
	DeletedOn      int64
	IsDel          int16
}

type PPost struct {
	ID              int64
	UserID          int64
	CommentCount    int64
	CollectionCount int64
	UpvoteCount     int64
	IsTop           int16
	IsEssence       int16
	IsLock          int16
	LatestRepliedOn int64
	Tags            string
	AttachmentPrice int64
	Ip              string
	IpLoc           string
	CreatedOn       int64
	ModifiedOn      int64
	DeletedOn       int64
	IsDel           int16
	Visibility      int16
	ShareCount      int64
}

type PPostAttachmentBill struct {
	ID         int64
	PostID     int64
	UserID     int64
	PaidAmount int64
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
}

type PPostCollection struct {
	ID         int64
	PostID     int64
	UserID     int64
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
}

type PPostContent struct {
	ID         int64
	PostID     int64
	UserID     int64
	Content    string
	Type       int16
	Sort       int16
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
}

type PPostStar struct {
	ID         int64
	PostID     int64
	UserID     int64
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
}

type PTag struct {
	ID         int64
	UserID     int64
	Tag        string
	QuoteNum   int64
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
}

type PTopicUser struct {
	ID         int64
	TopicID    int64
	UserID     int64
	AliasName  pgtype.Text
	Remark     pgtype.Text
	QuoteNum   pgtype.Int8
	IsTop      int16
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
	ReserveA   pgtype.Text
	ReserveB   pgtype.Text
}

// 用户
type PUser struct {
	ID       int64
	Nickname string
	Username string
	Phone    string
	// MD5密码
	Password string
	Salt     string
	// 状态, 1正常, 2停用
	Status int16
	Avatar string
	// 用户余额（分）
	Balance    int64
	IsAdmin    bool
	CreatedOn  int64
	ModifiedOn int64
	DeletedOn  int64
	IsDel      int16
}

type PWalletRecharge struct {
	ID          int64
	UserID      int64
	Amount      int64
	TradeNo     string
	TradeStatus string
	CreatedOn   int64
	ModifiedOn  int64
	DeletedOn   int64
	IsDel       int16
}

type PWalletStatement struct {
	ID              int64
	UserID          int64
	ChangeAmount    int64
	BalanceSnapshot int64
	Reason          string
	PostID          int64
	CreatedOn       int64
	ModifiedOn      int64
	DeletedOn       int64
	IsDel           int16
}
